export interface NCTBTopicDef {
  name: string;
}

export interface NCTBChapterOrModuleDef {
  name: string;
  topics: string[];
}

export interface NCTBSubjectDef {
  name: string;
  nameBn: string;
  slug: string;
  board: "madrasah";
  classLevel: "alim";
  streamGroup: "all" | "science" | "general_madrasah" | "quran_hadith";
  subjectType: "compulsory" | "group_elective" | "optional";
  structureType: "chapter" | "module";
  chaptersOrModules: NCTBChapterOrModuleDef[];
}

export const NCTB_CURRICULUM_DATA: NCTBSubjectDef[] = [
  {
    name: "Quran Mazid",
    nameBn: "কুরআন মাজিদ (২০১)",
    slug: "alim-quran-mazid",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Hadith & Usulul Hadith",
    nameBn: "হাদিস ও উসূলুল হাদিস (২০২)",
    slug: "alim-hadith",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Fiqh 1st Paper",
    nameBn: "আল ফিকহ ১ম পত্র (২০৩)",
    slug: "alim-fiqh-1",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Fiqh 2nd Paper",
    nameBn: "আল ফিকহ ২য় পত্র (২০৪)",
    slug: "alim-fiqh-2",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Arabic 1st Paper",
    nameBn: "আরবি ১ম পত্র (২০৫)",
    slug: "alim-arabic-1",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Arabic 2nd Paper",
    nameBn: "আরবি ২য় পত্র (২০৬)",
    slug: "alim-arabic-2",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Arabic (Science)",
    nameBn: "আরবি (বিজ্ঞান বিভাগ) (২২৩)",
    slug: "alim-arabic-science",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Balaghat & Mantiq",
    nameBn: "বালাগাত ও মানতিক (২১০)",
    slug: "alim-balaghat-mantiq",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Islamic History",
    nameBn: "ইসলামের ইতিহাস (২০৯)",
    slug: "alim-islamic-history",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Bangla 1st Paper",
    nameBn: "বাংলা ১ম পত্র (২৩৬)",
    slug: "alim-bangla-1",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Bangla 2nd Paper",
    nameBn: "বাংলা ২য় পত্র (২৩৭)",
    slug: "alim-bangla-2",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "English 1st Paper",
    nameBn: "ইংরেজি ১ম পত্র (২৩৮)",
    slug: "alim-english-1",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "English 2nd Paper",
    nameBn: "ইংরেজি ২য় পত্র (২৩৯)",
    slug: "alim-english-2",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "ICT",
    nameBn: "তথ্য ও যোগাযোগ প্রযুক্তি (২৪০)",
    slug: "alim-ict",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Civics 1st Paper",
    nameBn: "পৌরনীতি ও সুশাসন ১ম পত্র (২৪১)",
    slug: "alim-civics-1",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Civics 2nd Paper",
    nameBn: "পৌরনীতি ও সুশাসন ২য় পত্র (২৪২)",
    slug: "alim-civics-2",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Economics 1st Paper",
    nameBn: "অর্থনীতি ১ম পত্র (২১৩)",
    slug: "alim-economics-1",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Economics 2nd Paper",
    nameBn: "অর্থনীতি ২য় পত্র (২১৪)",
    slug: "alim-economics-2",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Physics 1st Paper",
    nameBn: "পদার্থবিজ্ঞান ১ম পত্র (২২৪)",
    slug: "alim-physics-1",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Physics 2nd Paper",
    nameBn: "পদার্থবিজ্ঞান ২য় পত্র (২২৫)",
    slug: "alim-physics-2",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Chemistry 1st Paper",
    nameBn: "রসায়ন ১ম পত্র (২২৬)",
    slug: "alim-chemistry-1",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Chemistry 2nd Paper",
    nameBn: "রসায়ন ২য় পত্র (২২৭)",
    slug: "alim-chemistry-2",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Biology 1st Paper",
    nameBn: "জীববিজ্ঞান ১ম পত্র (২৩০)",
    slug: "alim-biology-1",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Biology 2nd Paper",
    nameBn: "জীববিজ্ঞান ২য় পত্র (২৩১)",
    slug: "alim-biology-2",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Higher Math 1st Paper",
    nameBn: "উচ্চতর গণিত ১ম পত্র (২২৮)",
    slug: "alim-higher-math-1",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
  {
    name: "Higher Math 2nd Paper",
    nameBn: "উচ্চতর গণিত ২য় পত্র (২২৯)",
    slug: "alim-higher-math-2",
    board: "madrasah",
    classLevel: "alim",
    streamGroup: "all",
    subjectType: "compulsory",
    structureType: "chapter",
    chaptersOrModules: [],
  },
];
